In [3]:
pip install findspark

Collecting findspark
  Downloading findspark-2.0.0-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: findspark
Successfully installed findspark-2.0.0
Note: you may need to restart the kernel to use updated packages.

In [52]:
import findspark
from pyspark import SparkContext
from pyspark.sql import SparkSession, Window, Row
from pyspark.sql.functions import *
from pyspark.sql.types import *
import matplotlib.pyplot as plt

In [53]:
spark = SparkSession \
        .builder \
        .appName("firstSpark") \
        .getOrCreate()

In [54]:
def load_dataframe(filename):
    df = spark.read.format('csv').options(header='true').load(filename)
    return df

#creating a dataframe
df_matches = load_dataframe(r'C:\Users\sgondela\Documents\GitHub\Python\PySpark Certification\Project Driven Approach\Wrangling_PySpark-main\Data\Matches.csv')
df_matches.limit(5).show(10)

+--------+---+------+----------+-------------+--------------+----+----+---+
|Match_ID|Div|Season|      Date|     HomeTeam|      AwayTeam|FTHG|FTAG|FTR|
+--------+---+------+----------+-------------+--------------+----+----+---+
|       1| D2|  2009|2010-04-04|   Oberhausen|Kaiserslautern|   2|   1|  H|
|       2| D2|  2009|2009-11-01|  Munich 1860|Kaiserslautern|   0|   1|  A|
|       3| D2|  2009|2009-10-04|Frankfurt FSV|Kaiserslautern|   1|   1|  D|
|       4| D2|  2009|2010-02-21|Frankfurt FSV|     Karlsruhe|   2|   1|  H|
|       5| D2|  2009|2009-12-06|        Ahlen|     Karlsruhe|   1|   3|  A|
+--------+---+------+----------+-------------+--------------+----+----+---+

In [57]:
df_matches.createOrReplaceTempView('matches')

In [60]:
sql_matches = spark.sql('select * from matches where FTHG >0')
sql_matches.show()

+--------+---+------+----------+------------------+--------------+----+----+---+
|Match_ID|Div|Season|      Date|          HomeTeam|      AwayTeam|FTHG|FTAG|FTR|
+--------+---+------+----------+------------------+--------------+----+----+---+
|       1| D2|  2009|2010-04-04|        Oberhausen|Kaiserslautern|   2|   1|  H|
|       3| D2|  2009|2009-10-04|     Frankfurt FSV|Kaiserslautern|   1|   1|  D|
|       4| D2|  2009|2010-02-21|     Frankfurt FSV|     Karlsruhe|   2|   1|  H|
|       5| D2|  2009|2009-12-06|             Ahlen|     Karlsruhe|   1|   3|  A|
|       6| D2|  2009|2010-04-03|      Union Berlin|     Karlsruhe|   1|   1|  D|
|       7| D2|  2009|2009-08-14|         Paderborn|     Karlsruhe|   2|   0|  H|
|       9| D2|  2009|2009-09-26|    Kaiserslautern|     Karlsruhe|   2|   0|  H|
|      10| D2|  2009|2009-11-21|     Hansa Rostock|     Karlsruhe|   2|   1|  H|
|      11| D2|  2009|2009-12-19|    Greuther Furth|     Karlsruhe|   1|   4|  A|
|      12| D2|  2009|2010-04-16|           Koblenz|     Karlsruhe|   2|   2|  D|
|      13| D2|  2009|2010-03-21|        Oberhausen|     Karlsruhe|   1|   0|  H|
|      14| D2|  2009|2009-09-14|           Cottbus|     Karlsruhe|   2|   4|  A|
|      16| D2|  2009|2009-10-30|Fortuna Dusseldorf|     Karlsruhe|   1|   0|  H|
|      17| D2|  2009|2010-01-15|            Aachen|     Karlsruhe|   3|   1|  H|
|      18| D2|  2009|2009-10-18|          Augsburg|     Karlsruhe|   1|   1|  D|
|      19| D2|  2009|2010-02-05|          St Pauli|     Karlsruhe|   2|   1|  H|
|      20| D2|  2009|2009-08-24|       Munich 1860|     Karlsruhe|   1|   3|  A|
|      21| D1|  2009|2010-02-06|            Bochum|    Leverkusen|   1|   1|  D|
|      22| D1|  2009|2009-11-22|     Bayern Munich|    Leverkusen|   1|   1|  D|
|      23| D1|  2009|2010-05-08|        M'gladbach|    Leverkusen|   1|   1|  D|
+--------+---+------+----------+------------------+--------------+----+----+---+
only showing top 20 rows

In [50]:
#lets rename some of the columns
old_cols = df_matches.columns[-3:]
#df_matches.select(df_matches.columns[-3:]).show(10)

new_cols = ["HomeTeamGoals", "AwayTeamGoals", "FinalResult"]
old_new_cols = [*zip(old_cols, new_cols)]

print(old_new_cols)


for old_col,new_cols in old_new_cols:
    df_matches =df_matches.withColumnRenamed(old_col,new_cols)

df_matches.limit(5).toPandas()

[('HomeTeamWin', 'HomeTeamGoals'), ('AwayTeamWin', 'AwayTeamGoals'), ('GameTie', 'FinalResult')]

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,FinalResult,HomeTeamGoals,AwayTeamGoals,FinalResult
0,1,D2,2009,2010-04-04,Oberhausen,Kaiserslautern,2,1,H,1,0,0
1,2,D2,2009,2009-11-01,Munich 1860,Kaiserslautern,0,1,A,0,1,0
2,3,D2,2009,2009-10-04,Frankfurt FSV,Kaiserslautern,1,1,D,0,0,1
3,4,D2,2009,2010-02-21,Frankfurt FSV,Karlsruhe,2,1,H,1,0,0
4,5,D2,2009,2009-12-06,Ahlen,Karlsruhe,1,3,A,0,1,0

In [49]:

df_matches = df_matches \
    .withColumn('HomeTeamWin', when(col('FinalResult') == 'H', 1).otherwise(0)) \
    .withColumn('AwayTeamWin', when(col('FinalResult') == 'A', 1).otherwise(0)) \
    .withColumn('GameTie', when(col('FinalResult') == 'D', 1).otherwise(0))

df_matches.limit(5).toPandas()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,FinalResult,HomeTeamWin,AwayTeamWin,GameTie
0,1,D2,2009,2010-04-04,Oberhausen,Kaiserslautern,2,1,H,1,0,0
1,2,D2,2009,2009-11-01,Munich 1860,Kaiserslautern,0,1,A,0,1,0
2,3,D2,2009,2009-10-04,Frankfurt FSV,Kaiserslautern,1,1,D,0,0,1
3,4,D2,2009,2010-02-21,Frankfurt FSV,Karlsruhe,2,1,H,1,0,0
4,5,D2,2009,2009-12-06,Ahlen,Karlsruhe,1,3,A,0,1,0